name: Integrate NTQQ
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          export ELECTRON_SKIP_BINARY_DOWNLOAD=1
          npm install

      - name: Build
        run: npm run build

      - name: Download QQ
        run: |
          #wget https://github.com/linyuchen/LiteloaderQQNT-Integration/releases/download/win/win-x64-29456.zip
          wget https://github.com/linyuchen/LiteloaderQQNT-Integration/releases/download/win/win-x64-27597.zip
      - name: Extract QQ
        run: |
          #unzip win-x64-29456.zip
          #rm win-x64-29456.zip
          #mv QQNT QQNT-29456

          unzip win-x64-27597.zip
          rm win-x64-27597.zip
          mv QQNT QQNT-27597
      - name: Copy LLOneBot to QQ
        run: |
          #cp -r dist/ QQNT/versions/9.9.16-29456/resources/app/app_launcher/LiteLoaderQQNT/plugins/
          #mv QQNT/versions/9.9.16-29456/resources/app/app_launcher/LiteLoaderQQNT/plugins/dist QQNT/versions/9.9.16-29456/resources/app/app_launcher/LiteLoaderQQNT/plugins/LLOneBot

          cp -r dist/ QQNT-27597/resources/app/app_launcher/LiteLoaderQQNT/plugins/
          mv QQNT-27597/resources/app/app_launcher/LiteLoaderQQNT/plugins/dist QQNT-27597/resources/app/app_launcher/LiteLoaderQQNT/plugins/LLOneBot

      - name: Compress
        run: |
          sudo apt install zip -y
          zip -r LLOneBot_QQ27597_Windows_x64.zip QQNT-27597
          #zip -r LLOneBot_QQ29456.zip QQNT-29456
          cd ./dist/
          zip -r ../LLOneBot.zip ./*

      - name: Extract version from tag
        id: get-version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'LLOneBot.zip, LLOneBot_QQ27597_Windows_x64.zip'
          draft: true
          token: ${{ secrets.RELEASE_TOKEN }}
          name: LLOneBot v${{ steps.get-version.outputs.VERSION }}
          body: |
            **如果27597的 QQ 无法打开请先安装[vc140](https://github.com/linyuchen/LiteloaderQQNT-Integration/releases/download/win/vc140.x64.exe)**
